# Chapter 5: Getting Started with pandas

pandas support dataframes and dataframes operations. Dataframes can be heterogeneous, unlike arrays.

In [112]:
# Import packages
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

There are 2 main structures, `Series` and `DataFrame`.

### Series
A series is a 1D-array-like object containing a single sequence of values (same type) and associated indices. They can be created from lists, arrays, or dictionaries.

In [113]:
# Create via dictionary
obj = pd.Series({0: 4, 1: 7, 2: -5, 3: 3})

# Convert back to dictionary
obj.to_dict()

{0: 4, 1: 7, 2: -5, 3: 3}

In [114]:
# Create via list
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

Access the array and indices using associated methods.

In [115]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [116]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

The index can be set at the point of array creation. or be set afterwards

In [117]:
# Modify previous series
obj.index = ["d", "b", "a", "c"]
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [118]:
# Create new series
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

Subset using either position of variable or by name.

In [119]:
print(obj.iloc[[1, 2]])
print(obj.loc[["b", "a"]])

b    7
a   -5
dtype: int64
b    7
a   -5
dtype: int64

Boolean operations can be performed based on indices.

In [120]:
"b" in obj

True

If both a dictionary and an index is provided at creation of series, the custom index will be created first, then valid dictionary data will be appended to the series.

In [121]:
obj2 = pd.Series({"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000})

obj3 = pd.Series(
    {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000},
    index=["California", "Ohio", "Oregon", "Texas"],
)

# Note that the order of values doesn't match with dictionary order, but with indices.
obj2

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Arithmetic operations on series automatically aligns series by their index. Afterwards, the indices are also joined.

In [122]:
obj4 = obj2 + obj3
obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the series data and its index can have names.

In [123]:
obj4.name = "Population"
obj4.index.name = "State"
obj4

State
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
Name: Population, dtype: float64

### DataFrame

A dataframe is an ordered, named collection of columns. It can be constructed via a dictionary of equal-length 1D arrays.

In [124]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Similar to series, a list of column names can also be passed to order the data.

In [125]:
frame_ordered = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])
frame_ordered

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

Each column can be selected via subsetting or as an attribute.

In [126]:
frame_ordered[["year"]]

   year
0  2000
1  2001
2  2002
3  2001
4  2002
5  2003

In [127]:
frame_ordered.debt

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: debt, dtype: object

Note that attribute-based subsetting only works if the column name does not conflict with methods and is a valid name.

In [128]:
# This will call the method, not column 2
frame_ordered.pop

<bound method DataFrame.pop of    year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN>

Retrieve rows via row indices using `loc` or `iloc` as with Series

In [129]:
frame_ordered.loc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

Modify columns by assignment. If a series is assigned, the indices will be matched between the dataframe and series.

In [130]:
frame_ordered["debt"] = np.random.standard_normal(6)
frame_ordered

   year   state  pop      debt
0  2000    Ohio  1.5  0.328695
1  2001    Ohio  1.7  0.509192
2  2002    Ohio  3.6 -0.625453
3  2001  Nevada  2.4  2.589881
4  2002  Nevada  2.9  1.982482
5  2003  Nevada  3.2  0.782594

In [131]:
frame_ordered["debt"] = pd.Series([3, 5, 1], index=[2, 4, 5])
frame_ordered

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   3.0
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   5.0
5  2003  Nevada  3.2   1.0

The index and columns of DataFrames can have names.

In [132]:
frame_ordered.index.name = "no"
frame_ordered.columns.name = "Data"
frame_ordered

Data  year   state  pop  debt
no
0     2000    Ohio  1.5   NaN
1     2001    Ohio  1.7   NaN
2     2002    Ohio  3.6   3.0
3     2001  Nevada  2.4   NaN
4     2002  Nevada  2.9   5.0
5     2003  Nevada  3.2   1.0

DataFrames can be turned into arrays.

In [133]:
frame_ordered.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, 3.0],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, 5.0],
       [2003, 'Nevada', 3.2, 1.0]], dtype=object)

## Essential Functionality

### Reindexing

Use reindexing to create a new dataframe / series from the current dataframe, with new indices following the usual syntax.

In [134]:
# Create Series
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

# Expand indices
obj4 = obj3.reindex(np.arange(6))

# Expand indices, interpolate NAs
obj5 = obj3.reindex(np.arange(6), method="ffill")
print("obj3\n", obj3)
print("obj4\n", obj4)
print("obj5\n", obj5)

obj3
 0      blue
2    purple
4    yellow
dtype: object
obj4
 0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object
obj5
 0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With dataframes, reindex rows with the `index` arg, reindex columns with the `columns` arg.

In [135]:
# Example df
frame_ordered

Data  year   state  pop  debt
no
0     2000    Ohio  1.5   NaN
1     2001    Ohio  1.7   NaN
2     2002    Ohio  3.6   3.0
3     2001  Nevada  2.4   NaN
4     2002  Nevada  2.9   5.0
5     2003  Nevada  3.2   1.0

In [136]:
# Reindex
frame_ordered.reindex(index = [0, 1, 3, 4], columns = ["year", "pop"])

Data  year  pop
no
0     2000  1.5
1     2001  1.7
3     2001  2.4
4     2002  2.9

### Dropping Entries from an Axis

Similar logic as reindex - pass index and columns labels to drop from data. Note that this does not mutate the original objects.

In [137]:
# Drop on series
obj5.drop([0, 2, 4])

1      blue
3    purple
5    yellow
dtype: object

In [138]:
# Drop on DataFrame
frame_ordered.drop(index=[2, 5], columns=["debt"])

Data  year   state  pop
no
0     2000    Ohio  1.5
1     2001    Ohio  1.7
3     2001  Nevada  2.4
4     2002  Nevada  2.9

### Indexing, Selection, and Filtering

Use the `loc` and `iloc` methods to subset Series and DataFrames based on indices.

In [139]:
frame_ordered.iloc[1:5, 1:4]

Data   state  pop  debt
no
1       Ohio  1.7   NaN
2       Ohio  3.6   3.0
3     Nevada  2.4   NaN
4     Nevada  2.9   5.0

In [140]:
frame_ordered.loc[[0, 1, 2],["state", "debt"]]

Data state  debt
no
0     Ohio   NaN
1     Ohio   NaN
2     Ohio   3.0

### Arithmetic and Data Alignment

Pandas automatically align Series and DataFrames by their indexes during math operations. However, during these operations, missing values propagate.

In [141]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [142]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

By performing additions using appropriate methods and the `fill` argument, missing values can be filled automatically (prior operation).

In [143]:
s1.add(s2, fill_value=0)

a    5.2
c    1.1
d    3.4
e    0.0
f    4.0
g    3.1
dtype: float64

#### Operations between DataFrame and Series

When a math operation is performed on a DataFrame on a Series, it is by default performed row by row. Pass the `axis` arg to methods to perform it by column instead.

In [144]:
# Set up data
frame = pd.DataFrame(
    np.arange(12.0).reshape((4, 3)),
    columns= ["b", "d", "e"],
    index=["Utah", "Ohio", "Texas", "Oregon"]
)

rows = pd.Series([4, 3, 2, 1], index=["Utah", "Ohio", "Texas", "Oregon"])

columns = pd.Series([3, 2, 1], index = ["b", "d", "e"])

print(frame)
print(columns)
print(rows)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    3
d    2
e    1
dtype: int64
Utah      4
Ohio      3
Texas     2
Oregon    1
dtype: int64

In [145]:
# Perform operation per row
frame * columns

           b     d     e
Utah     0.0   2.0   2.0
Ohio     9.0   8.0   5.0
Texas   18.0  14.0   8.0
Oregon  27.0  20.0  11.0

In [147]:
# Perform per column
frame.add(rows, axis = "index")

           b     d     e
Utah     4.0   5.0   6.0
Ohio     6.0   7.0   8.0
Texas    8.0   9.0  10.0
Oregon  10.0  11.0  12.0

### Function Application and Mapping

### Axis Indexes with Duplicate Labels

## Summarizing and Computing Descriptive Statistics

### Correlation and Covariance

### Unique Values, Value Counts, and Membership